name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.25.0
    with:
      image: ghcr.io/radiorabe/pathfinderevents
      name: pathfinderevents
      display-name: Subscribe to Pathfinder changes and emit CloudEvents on change
      tags: minimal rhel9 ubi9 rabe kafka cloudevents pathfinder axia
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@v0.25.0
