name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@c7aef9928f610ec51b44f84debf2321189276d54 # v0.41.3
    with:
      image: ghcr.io/radiorabe/pathfinderevents
      name: pathfinderevents
      display-name: Subscribe to Pathfinder changes and emit CloudEvents on change
      tags: minimal rhel9 ubi9 rabe kafka cloudevents pathfinder axia
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@c7aef9928f610ec51b44f84debf2321189276d54 # v0.41.3
